name: Sync Helm Chart

on:
  workflow_dispatch:

jobs:
  sync-chart:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::545217747931:role/ECR_Full
          aws-region: us-east-1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configure Helm OCI Credential Helper for ECR
        run: |
          mkdir -p ~/.config/helm
          cat <<EOF > ~/.config/helm/registry.json
          {
            "credHelpers": {
              "545217747931.dkr.ecr.us-east-1.amazonaws.com": "ecr-login"
            }
          }
          EOF

      - name: Pull and Push Helm Chart to ECR (OCI)
        run: |
          set -e

         CHART_NAME=$(jq -r '.[0].chart' charts.json)
         VERSION=$(jq -r '.[0].version' charts.json)
         REPO_URL=$(jq -r '.[0].helm_repo' charts.json)

         echo "Chart: $CHART_NAME"
         echo "Version: $VERSION"
         echo "Helm Repo: $REPO_URL"

         helm repo add $CHART_NAME $REPO_URL
         helm repo update

         helm pull $CHART_NAME/$CHART_NAME --version $VERSION

         REGISTRY="545217747931.dkr.ecr.us-east-1.amazonaws.com"

         helm chart save $CHART_NAME-$VERSION.tgz oci://$REGISTRY/kyverno-chart:$VERSION
         helm chart push oci://$REGISTRY/kyverno-chart:$VERSION
         
