name: Sync Helm Chart

on:
  push:
    paths:
      - charts.json

jobs:
  sync-chart:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<your-account-id>:role/<your-gha-role>
          aws-region: us-east-1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull and Push Helm Chart to ECR
        run: |
          CHART_NAME=$(jq -r '.[0].name' charts.json)
          VERSION=$(jq -r '.[0].version' charts.json)
          REPO_URL=$(jq -r '.[0].url' repos.json)

          helm repo add $CHART_NAME $REPO_URL
          helm repo update
          helm pull $CHART_NAME/$CHART_NAME --version $VERSION
          
          REGISTRY=$(aws ecr describe-registry --query "registryId" --output text).dkr.ecr.us-east-1.amazonaws.com
          helm push $CHART_NAME-$VERSION.tgz oci://$REGISTRY/helm-charts
